services:
  db:
    image: mongo:latest
    environment:
      - MONGO_INITDB_DATABASE=detect_db
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=pass
    volumes:
      - ./data:/data/db
    ports:
      - 27019:27017
      